services:
  backend:
    image: task6
    ports:
      - "8080:8080"
    environment:
      - PREDICTIONS_STREAM_NAME=Task6_int
      - RUN_ID= Task6
      - AWS_DEFAULT_REGION=eu-west-1
      - MODEL_LOCATION=/app/model
      - KINESIS_ENDPOINT_URL=http://kinesis:4566/
    volumes:
      - "./model:/app/model"
  kinesis:
    image: localstack/localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=kinesis
    volumes:
      - ./aws:/docker-entrypoint-initaws.d